name : zhangsan

person:
  name: lisi
  age : 18
  sex : 1


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miao?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  type-aliases-package: com.qwe.pojo
  mapper-locations: classpath:mapper/*.xml
